### PR TITLE
Heatroom data to east & croc. New junction in Single Chamber.

### PR DESCRIPTION
**Pull request by DIProgan**
You feel something burning?

### CODE REVIEW

**Comment by DIProgan** [comment]
The only relevant commit still in this should be the Boyon change, the rest can be discarded.

**Comment by miketrethewey** [comment]
For future reference, that's commit 61fc8cb.

**Comment by fdtaillefer** [comment]
Do you want to put that commit into another PR? Can't really pick and choose what to merge here.

**Comment by DIProgan** [comment]
Git sucks :P I'll do it somewhere else then ^^

**Comment by fdtaillefer** [comment]
Done by commit `0aebac6`

**Pull request closed without merging**
